# Generated by Django 4.0.2 on 2022-02-20 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_by_email', '0002_alter_djgrammuser_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='following',
            name='unique_follow',
        ),
    ]
