services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: backend_db
      POSTGRES_USER: dj_gramm
      POSTGRES_PASSWORD: dj_pass
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile_dev
    volumes:
      - ./backend:/code
    env_file:
      - ./backend/.env
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    links:
      - db