version: '3.8'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: backend_db
      POSTGRES_USER: dj_gramm
      POSTGRES_PASSWORD: dj_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app/
    env_file:
      - backend/.env
    ports:
      - "8000:8000"
    links:
      - db
volumes:
  postgres_data: