# Generated by Django 4.0 on 2022-02-05 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gramm_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='like',
            name='unique_like',
        ),
    ]
