# Generated by Django 3.2.9 on 2021-11-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_by_email', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='djgrammuser',
            options={'permissions': [('can_create_post', 'Can create post'), ('can_change_post', 'Can change post'), ('post.can_view', 'Can view post'), ('post.can_edit', 'Can edit post')]},
        ),
        migrations.AlterField(
            model_name='djgrammuser',
            name='avatar',
            field=models.ImageField(upload_to='auth_by_email/users_avatars'),
        ),
    ]
