# Generated by Django 3.2.9 on 2021-11-30 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_by_email', '0002_auto_20211130_2021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='djgrammuser',
            options={'permissions': [('gramm_app.create_post', 'Can create post'), ('gramm_app.edit_post', 'Can change post'), ('gramm_app.view_post', 'Can view post'), ('gramm_app.delete_post', 'Can delete post'), ('gramm_app.view_posts', 'Can view all posts')]},
        ),
    ]
