# Generated by Django 4.0.2 on 2022-02-14 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_by_email', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='djgrammuser',
            options={},
        ),
    ]
